sudo: false

os: linux
dist: xenial

language: c
python: 3.7

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - ninja

before_install:
  - pip3 install meson

script:
  - mkdir build
  - meson build
  - meson test -C build --verbose --werror --enable-gcov

