language: c
script:
  - make test
env: CFLAGS=-Werror
compiler:
  - clang
  - gcc

jobs:
  include:
    - stage: coverage
      compiler: gcc
      install:
        - pip install --user cpp-coveralls
      script:
        - make test
      after_success:
        - coveralls -i src/idx.c --gcov-options '\-lpo build/lib'
      env:
        - DEBUG=1
        - COVERAGE=1
