sudo: false

os: linux
dist: xenial

language: python
python: 3.7

matrix:
  include:
    - env: CC=gcc
    - env: CC=clang

before_install:
  - wget https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip
  - unzip ninja-linux.zip -d ninja
  - export PATH="$PWD/ninja:$PATH"
  - chmod 755 ninja/ninja
  - pip install meson

install:
  - meson build --warnlevel=3 --werror

script:
  - meson test -C build --print-errorlogs

